import "@/styles/globals.css";
import Providers from "@/context/Providers";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <header>
            <div className={`flex justify-between px-4`}>
              <nav>
                <Link href="/">
                  <span
                    className={`text-slate-700 hover:text-primary-500 font-semibold`}
                  >
                    Home
                  </span>
                </Link>
              </nav>
              <div>
                <span>login coming soon</span>
              </div>
            </div>
          </header>
          <main>{children}</main>
        </body>
      </Providers>
    </html>
  );
}
